### ISSUE TITLE
Portnumbers for ACK and OFFER are not correct

### ISSUE THREAD

**Issue by wvandervaart** [azdolinski/python_ztp#1]
The source and destination port on these two packets are swapped.
To fix it I changed the following lines:
OLD lines:
236         sport = packet[UDP].sport
237         dport = packet[UDP].dport
279         sport = packet[UDP].sport
280         dport = packet[UDP].dport
NEW lines:
236         sport = packet[UDP].dport
237         dport = packet[UDP].sport
279         sport = packet[UDP].dport
280         dport = packet[UDP].sport

**Comment by azdolinski** [comment]
Indeed... outgoing packets should have switched src<->dst port.
Fixed in 0.6b.
Thanks.
